"""initial

Revision ID: 1eee35703347
Revises: 
Create Date: 2025-12-16 14:31:34.352316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Added manually


# revision identifiers, used by Alembic.
revision: str = '1eee35703347'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('product', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('product', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product', 'target_price',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'target_price',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('product', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('product', 'error_message')
    op.drop_column('product', 'status')
    # ### end Alembic commands ###
